# Generated by Django 4.0.3 on 2022-06-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('author', models.CharField(max_length=140)),
                ('year', models.IntegerField()),
                ('finished', models.BooleanField()),
            ],
        ),
    ]
